import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
	title: "NotebookLLM",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className="min-h-screen h-screen overflow-hidden flex flex-col">
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
